spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/mangpo
    username: root
    password:
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      #      generate-ddl: true
      ddl-auto: update
    properties:
      hibernate:
        #       show_sql: true
        format_sql: true

  servlet:
    multipart:
      maxFileSize: 30MB
      maxRequestSize: 30MB

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace

#
#spring:
#  datasource:
#    url: ${RDS_URL}
#    username: ${RDS_USERNAME}
#    password: ${RDS_PASSWORD}
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      generate-ddl: true
#      ddl-auto: update
#    properties:
#      hibernate:
#        #       show_sql: true
#        format_sql: true
#
#  servlet:
#    multipart:
#      maxFileSize: 30MB
#      maxRequestSize: 30MB
#
#logging.level:
#  org.hibernate.SQL: debug
## org.hibernate.type: trace



cloud:
  aws:
    s3:
      bucket: elasticbeanstalk-ap-northeast-2-081654662783
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true

